Update

diff --git a/scripts/backup b/scripts/backup
--- a/scripts/backup
+++ b/scripts/backup
@@ -1,14 +1,18 @@
 #!/bin/bash
 
 date=`date -Is`
-backups_dir="/mnt/hdd/backups"
-logfile="$backups_dir/archlinuxbackup.log"
-backup_arch="$backups_dir/archlinux/"
+backup_dir="/mnt/backup"
+logfile="$backup_dir/archlinuxbackup.log"
+backup_arch="$backup_dir/archlinux/"
 exclude_file="/home/vincent/dotfiles/scripts/backup_ignore.txt"
 
-echo "Backing up to $backup_arch"
 
-mkdir -p $backup_arch
+if ! mountpoint -q $backup_dir ; then 
+  echo "Error: $backup_dir not mounted"
+  exit 1
+fi
+
+echo "Backing up to $backup_arch"
 
 # Option -a doesn't work with exfat because of permissions
 #
